### PR TITLE
Feat typescript test

### PR DESCRIPTION
**Pull request by telekosmos**
Tests improved (some of them rewritten) for both generator and generated app(s).
No functional changes on the generated skeleton

### CODE REVIEW

**Comment by kristianmandrup** [comment]
OK, I will try but expect it is "good to go" now ;)

**Comment by kristianmandrup** [comment]
Yup, looks awesome!!!

``` sh
$ npm publish
+ generator-aurelia-ts@0.0.1
```

Now it's out in the WILD!!!

**Comment by telekosmos** [comment]
It can be ok, but after reading [this](http://blog.durandal.io/2015/07/02/aurelia-oslo-video-pluralsight-new-releases-typescript-support-more/) also can be a bit out of date :-/. Try to update ASAIC (as soon as i can :) even knowing they will be also temporary

**Comment by telekosmos** [comment]
Cool for `npm publish`:-D

**Pull request merged**
