### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by telekosmos**
Just enhance and refactor lots of tests for the generators. Based on the current codebase and the documentation :). No new functionality added, just fixing minor bugs which didn't pass the tests. 
The PR seems to be ok, but try to do a `mocha` just to be sure there are 88 tests passing.

### CODE REVIEW

**Comment by kristianmandrup** [comment]
Awesome!!! I will try it out :) Any suggestions for improvements?

**Comment by telekosmos** [comment]
Hi
TBH, I'd get the generator as stable as possible. I've seen few things which are inconsistent -options vs prompts,...- and people can try things which does not work, as I see the (parent) generator has loads of features :-D, which is great.
 You just have to check the amount of tests, lets say 70 different tests for generator features - if you run mocha, you will get 88, but many tests are only initial test to check the generator tested just works-.
The SASS syntax addition can be ok. I wanted to send this PR as adding the SASS syntax involved quite a few changes a didn't want to mix with the test specific ones. In fact, I'd change the current SASS name to SCSS to make space for the new feature, so you'd have, lets say, the --scss and --sass options -ideally mutually exclusive-. Dunno how you get this proposal :-)

And, regarding to the ui/css frameworks, I'm confused with couple of things:- 'primary' framework means the application is built with that framework by default, and you can have another one just in case you want to use some components, don't you?
- so, I though the --ui option meant the primary framework, and you could choose more framework by prompts, but I dunno whether or not this is right the semantic.
  Let me know if you have any issue on merging the PR!!!Cheers!
  w i l l y

-- Guillermo C. Martínez 

```
 On Monday, August 17, 2015 1:24 PM, Kristian Mandrup <notifications@github.com> wrote:
```

 Awesome!!! I will try it out :) Any suggestions for improvements?—

**Comment by kristianmandrup** [comment]
Hi @telekosmos :)

I trust your judgements and you are most welcome to streamline the generators, esp. how it uses options vs prompts. The idea of the options is obviously to preselect certain prompt selections or even skip the prompt entirely. I agree that the --ui option should be used to select primary UI framework.
I also like your ideas regarding scss vs sass. I think “everyone” are using scss these days…?
Cheers! Thanks a lot for your effort :)

Kristian

I merged the PR, rant the tests and made a new release 0.8 already. Getting closer to 1.0.rc.

**Comment by telekosmos** [comment]
Hi thereYou're right about options and prompts, but watching a bit the code is like you didn't took so many into account. The yeoman documentation is sparse and a bit confusing sometimes and is not very clear how to use options vs prompts. Even, I saw you used sometimes phase1/2 in prompts, but you have a -more or less hidden- when function in prompt objects which is kind of conditional for a prompt in particular. So, maybe we can use it to skip prompts at all or at least some of them.
I use SASS rather than scss :-D. Can be the freak out there haha, but just for style code I think semicolons and brackets can be disposable. In fact, that is one of the very first things you read about stylus in their website.
Keep going!!
w i l l y

```
 On Monday, August 17, 2015 5:42 PM, Kristian Mandrup <notifications@github.com> wrote:
```

 Hi @telekosmos :)I trust your judgements and you are most welcome to streamline the generators, esp. how it uses options vs prompts. The idea of the options is obviously to preselect certain prompt selections or even skip the prompt entirely. I agree that the --ui option should be used to select primary UI framework.
I also like your ideas regarding scss vs sass. I think “everyone” are using scss these days…?
Cheers! Thanks a lot for your effort :)KristianI merged the PR, rant the tests and made a new release 0.8 already. Getting closer to 1.0.rc.—

**Comment by kristianmandrup** [comment]
Yeah, the Yeoman docs are really bad :( a pity. I've been using Slush lately with some success, but has less direct API support, so you are more on your own for good or bad...

Yeah, I hate all that noise from `;` and `{` as well. I used to develop using LiveScript for quite a while! 
I also use Jade for HTML. Please see if you can improve the multi-stage prompts and the options/prompts/arguments when/if you have the time and send me a PR. 
Thanks again :)

**Pull request merged**
